# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'TakeIt' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TakeIt
	pod 'Firebase/Core', '~> 5.15.0'
	pod 'Firebase/Auth', '~> 5.15.0'
	pod 'Firebase/Messaging', '~> 5.15.0'
	pod 'Firebase/Storage', '~> 5.15.0'
	pod 'GoogleSignIn'
	pod 'Google-Mobile-Ads-SDK'

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  target 'TakeItTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'TakeIt-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TakeIt-tvOS

  target 'TakeIt-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
