const types = {
  FORCE_REFRESH_MAIN: "FORCE_REFRESH_MAIN",
  IS_FROM_LOGIN: "IS_FROM_LOGIN",
  IS_FROM_LOADING: "IS_FROM_LOADING",
  SET_ACTIVE_FOOTER_BTN: "SET_ACTIVE_FOOTER_BTN"
};

export default types;
