const types = {
  SET_USER_INFO: "SET_USER_INFO",
  SET_USER_CONTINUOUS_EXERCISE_DAYS: "SET_USER_CONTINUOUS_EXERCISE_DAYS",
  SET_USER_FAT_PER: "SET_USER_FAT_PER",
  SET_USER_MUSCLE_PER: "SET_USER_MUSCLE_PER",
  SET_USER_BMI_PER: "SET_USER_BMI_PER",
  SET_TODAY_USER_EXERCISE_LIST: "SET_TODAY_USER_EXERCISE_LIST"
};

export default types;
